### ISSUE TITLE
How comptaible is the postgres output with discogs-xml2db

### ISSUE THREAD

**Issue by ijabz** [alvare/discogs2pg#5]
You have done exactly what I wanted to do with https://github.com/philipmat/discogs-xml2db/issues/35
I'm tempted to swap to your project but i know less about Haskell than I even did about Python, so I am hesitant, do you know what differences the are between the tables generated by the two approaches ?

**Comment by clrnd** [comment]
Well, I know they are very similar, since I basically copied [their file](https://github.com/philipmat/discogs-xml2db/blob/master/create_tables.sql) and modified it a little to accommodate schema changes and subjective preferences.

I did a kind of diff but it's hard to read, also some are just name changes.

The Haskell code here is quite simple (and a little outdated), if that matters. There is also a binary release I think 🤔
